app:
  run_mode: "debug"
  cancel_timeout: "5s"

server:
  http_port: 18020
  read_header_timeout: "5s"

mysql:
  user: "root"
  password: "Aa22128588"
  #127.0.0.1:3306
  host: "127.0.0.1"
  name: "ty_tsrc"
  debug: true

redis:
  user: ""
  password: ""
  #127.0.0.1:3306
  host: "127.0.0.1:6379"
  database: 0
  idleTimeout: "200s"

bigcache:
  life_window: "600s"

log:
  log_path: "C:\\Users\\user\\Documents\\eyee_tech_vacuum\\log\\log.txt"
  application_name: "環揚環保-真空系統監控工程"
  debug: true

linenotify:
  token: "3GYFrCvlvUxICp0u45uLXRweXMseSMPjlSleq79DSos"

ratelimit:
  limit_per_minute: 600

jwt:
  expiration: "1d" #1 day
